.\" $Id: login_fingerprint.8,v 1.3 2009/05/30 15:23:51 robert Exp $
.\"
.\" Copyright (c) 2009 Robert Nagy <robert@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: May 30 2009 $
.Dt LOGIN_FINGERPRINT 8
.Os
.Sh NAME
.Nm login_fingerprint
.Nd provides authentication via fingerprints
.Sh SYNOPSIS
.Nm login_fingerprint
.Op Fl s Ar service
.Op Fl v Ar name=value
.Ar user
.Op Ar class
.Sh DESCRIPTION
The
.Nm
utility is called by
.Xr login 1 ,
.Xr su 1 ,
and others to authenticate the
.Ar user
with fingerprint authentication.
.Pp
The
.Ar user
argument is the login name of the user to be authenticated.
.Pp
The
.Ar service
argument specifies which protocol to use with the
invoking program.
The only allowed protocols is
.Em login .
.Pp
.Sh LOGIN.CONF VARIABLES
The
.Nm
utility requires the following
.Xr login.conf 5
variables:
.Bl -tag -width x-fingerprint
.It x-fingerprint
Use the fingerprint on the specified finger for authorization.
Each finger is associated with a number between 1 and 10:
.Bl -tag -width x-fingerprint
.It Er 1 Em "Left thumb" .
.It Er 2 Em "Left index" .
.It Er 3 Em "Left middle" .
.It Er 4 Em "Left ring" .
.It Er 5 Em "Left small" .
.It Er 6 Em "Right thumb" .
.It Er 7 Em "Right index" .
.It Er 8 Em "Right middle" .
.It Er 9 Em "Right ring" .
.It Er 10 Em "Right small" .
.Pp
.Sh SEE ALSO
.Xr login 1 ,
.Xr su 1 ,
.Xr login.conf 5 ,
.Xr ugen 4
