#!/bin/sh

prefix="/usr/X11R6"
exec_prefix="${prefix}"

# !!!! Taken out.
#${exec_prefix}/bin/xsetroot -fg \#6f6f6f -bg \#bfbfbf -bitmap ${prefix}/include/X11/bitmaps/root_weave
#${exec_prefix}/bin/xconsole -geometry 480x130-0-0 -daemon -notify -verbose -fn fixed -exitOnFail
#  install package openbsd-backgrounds
#  then uncomment:
#
# if test -x /usr/local/bin/openbsd-wallpaper
# then
#   /usr/local/bin/openbsd-wallpaper
# fi
# sxpm OpenBSD.xpm &

# !!!! Add this. Set up displays.
if [ -x /etc/X11/xenodm/x-displays ]
then
	/etc/X11/xenodm/x-displays
fi

# Light numlock.
#if [ -x /usr/local/bin/numlockx ]
#then
#	/usr/local/bin/numlockx
#fi

